import { Inter } from "next/font/google";
import "./globals.css";
import Providers from '../redux/providers'

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
	title: "React-Devices-Frontend",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<Providers>
			<body className={inter.className}>
				{children}	
				</body>		
			</Providers>
		</html>
	);
}
